using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyAutomate.Migrations
{
    /// <inheritdoc />
    public partial class TableChange24 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DeviceNoahInfo");

            migrationBuilder.CreateTable(
                name: "DeviceMinInfoData",
                columns: table => new
                {
                    serialNum = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    id = table.Column<int>(type: "int", nullable: false),
                    portName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    dataLogSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    groupId = table.Column<int>(type: "int", nullable: false),
                    alias = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    location = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    addr = table.Column<int>(type: "int", nullable: false),
                    fwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    model = table.Column<long>(type: "bigint", nullable: false),
                    innerVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    lost = table.Column<bool>(type: "bit", nullable: false),
                    status = table.Column<int>(type: "int", nullable: false),
                    tcpServerIp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    lastUpdateTime = table.Column<long>(type: "bigint", nullable: false),
                    sysTime = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    deviceType = table.Column<int>(type: "int", nullable: false),
                    communicationVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    pmax = table.Column<int>(type: "int", nullable: false),
                    comAddress = table.Column<int>(type: "int", nullable: false),
                    dtc = table.Column<int>(type: "int", nullable: false),
                    countrySelected = table.Column<int>(type: "int", nullable: false),
                    startTime = table.Column<int>(type: "int", nullable: false),
                    restartTime = table.Column<int>(type: "int", nullable: false),
                    wselectBaudrate = table.Column<int>(type: "int", nullable: false),
                    trakerModel = table.Column<int>(type: "int", nullable: false),
                    priorityChoose = table.Column<int>(type: "int", nullable: false),
                    batteryType = table.Column<int>(type: "int", nullable: false),
                    batSeriesNum = table.Column<int>(type: "int", nullable: false),
                    batParallelNum = table.Column<int>(type: "int", nullable: false),
                    bctMode = table.Column<int>(type: "int", nullable: false),
                    bctAdjust = table.Column<int>(type: "int", nullable: false),
                    bagingTestStep = table.Column<int>(type: "int", nullable: false),
                    vnormal = table.Column<double>(type: "float", nullable: false),
                    mppt = table.Column<double>(type: "float", nullable: false),
                    batTempLowerLimitD = table.Column<double>(type: "float", nullable: false),
                    batTempUpperLimitD = table.Column<double>(type: "float", nullable: false),
                    batTempLowerLimitC = table.Column<double>(type: "float", nullable: false),
                    batTempUpperLimitC = table.Column<double>(type: "float", nullable: false),
                    vbatWarning = table.Column<double>(type: "float", nullable: false),
                    vbatWarnClr = table.Column<double>(type: "float", nullable: false),
                    modbusVersion = table.Column<int>(type: "int", nullable: false),
                    manufacturer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bdc1Sn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bdc1Model = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bdc1Version = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    vbatStopForDischarge = table.Column<double>(type: "float", nullable: false),
                    vbatStopForCharge = table.Column<double>(type: "float", nullable: false),
                    vbatStartForDischarge = table.Column<double>(type: "float", nullable: false),
                    userName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    modelText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    plantId = table.Column<int>(type: "int", nullable: false),
                    plantname = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    timezone = table.Column<double>(type: "float", nullable: false),
                    pCharge = table.Column<double>(type: "float", nullable: false),
                    pDischarge = table.Column<double>(type: "float", nullable: false),
                    updating = table.Column<bool>(type: "bit", nullable: false),
                    power = table.Column<double>(type: "float", nullable: false),
                    eToday = table.Column<double>(type: "float", nullable: false),
                    eTotal = table.Column<double>(type: "float", nullable: false),
                    energyMonth = table.Column<double>(type: "float", nullable: false),
                    strNum = table.Column<int>(type: "int", nullable: false),
                    liBatteryManufacturers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    liBatteryFwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bmsSoftwareVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bmsCommunicationType = table.Column<int>(type: "int", nullable: false),
                    monitorVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    bdcMode = table.Column<int>(type: "int", nullable: false),
                    bdcAuthversion = table.Column<int>(type: "int", nullable: false),
                    hwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    vppOpen = table.Column<int>(type: "int", nullable: false),
                    level = table.Column<int>(type: "int", nullable: false),
                    lastUpdateTimeText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    treeName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    treeID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    parentID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    imgPath = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    statusText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    powerMaxText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    energyMonthText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TS = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceMinInfoData", x => x.serialNum);
                });

            migrationBuilder.CreateTable(
                name: "DeviceMinLastData",
                columns: table => new
                {
                    SerialNum = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Time = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Address = table.Column<int>(type: "int", nullable: false),
                    Again = table.Column<bool>(type: "bit", nullable: false),
                    Alias = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BatSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BatteryNo = table.Column<int>(type: "int", nullable: false),
                    BatterySN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bdc1ChargePower = table.Column<double>(type: "float", nullable: false),
                    Bdc1ChargeTotal = table.Column<double>(type: "float", nullable: false),
                    Bdc1DischargePower = table.Column<double>(type: "float", nullable: false),
                    Bdc1DischargeTotal = table.Column<double>(type: "float", nullable: false),
                    Bdc1FaultType = table.Column<int>(type: "int", nullable: false),
                    Bdc1Ibat = table.Column<double>(type: "float", nullable: false),
                    Bdc1Ibb = table.Column<double>(type: "float", nullable: false),
                    Bdc1Illc = table.Column<double>(type: "float", nullable: false),
                    Bdc1Mode = table.Column<int>(type: "int", nullable: false),
                    Bdc1Soc = table.Column<int>(type: "int", nullable: false),
                    Bdc1Status = table.Column<int>(type: "int", nullable: false),
                    Bdc1Temp1 = table.Column<double>(type: "float", nullable: false),
                    Bdc1Temp2 = table.Column<double>(type: "float", nullable: false),
                    Bdc1Vbat = table.Column<double>(type: "float", nullable: false),
                    Bdc1Vbus1 = table.Column<double>(type: "float", nullable: false),
                    Bdc1Vbus2 = table.Column<double>(type: "float", nullable: false),
                    Bdc1WarnCode = table.Column<int>(type: "int", nullable: false),
                    Bdc2ChargePower = table.Column<double>(type: "float", nullable: false),
                    Bdc2ChargeTotal = table.Column<double>(type: "float", nullable: false),
                    Bdc2DischargePower = table.Column<double>(type: "float", nullable: false),
                    Bdc2DischargeTotal = table.Column<double>(type: "float", nullable: false),
                    Bdc2FaultType = table.Column<int>(type: "int", nullable: false),
                    Bdc2Ibat = table.Column<double>(type: "float", nullable: false),
                    Bdc2Ibb = table.Column<double>(type: "float", nullable: false),
                    Bdc2Illc = table.Column<double>(type: "float", nullable: false),
                    Bdc2Mode = table.Column<int>(type: "int", nullable: false),
                    Bdc2Soc = table.Column<int>(type: "int", nullable: false),
                    Bdc2Status = table.Column<int>(type: "int", nullable: false),
                    Bdc2Temp1 = table.Column<double>(type: "float", nullable: false),
                    Bdc2Temp2 = table.Column<double>(type: "float", nullable: false),
                    Bdc2Vbat = table.Column<double>(type: "float", nullable: false),
                    Bdc2Vbus1 = table.Column<double>(type: "float", nullable: false),
                    Bdc2Vbus2 = table.Column<double>(type: "float", nullable: false),
                    Bdc2WarnCode = table.Column<int>(type: "int", nullable: false),
                    BdcBusRef = table.Column<int>(type: "int", nullable: false),
                    BdcDerateReason = table.Column<int>(type: "int", nullable: false),
                    BdcFaultSubCode = table.Column<int>(type: "int", nullable: false),
                    BdcStatus = table.Column<int>(type: "int", nullable: false),
                    BdcVbus2Neg = table.Column<double>(type: "float", nullable: false),
                    BdcWarnSubCode = table.Column<int>(type: "int", nullable: false),
                    BgridType = table.Column<int>(type: "int", nullable: false),
                    BMerterConnectFlag = table.Column<int>(type: "int", nullable: false),
                    BmsCommunicationType = table.Column<int>(type: "int", nullable: false),
                    BmsCvVolt = table.Column<double>(type: "float", nullable: false),
                    BmsError2 = table.Column<int>(type: "int", nullable: false),
                    BmsError3 = table.Column<int>(type: "int", nullable: false),
                    BmsError4 = table.Column<int>(type: "int", nullable: false),
                    BmsFaultType = table.Column<int>(type: "int", nullable: false),
                    BmsFwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BmsIbat = table.Column<double>(type: "float", nullable: false),
                    BmsIcycle = table.Column<int>(type: "int", nullable: false),
                    BmsInfo = table.Column<double>(type: "float", nullable: false),
                    BmsIosStatus = table.Column<int>(type: "int", nullable: false),
                    BmsMaxCurr = table.Column<double>(type: "float", nullable: false),
                    BmsMcuVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BmsPackInfo = table.Column<double>(type: "float", nullable: false),
                    BmsSoc = table.Column<int>(type: "int", nullable: false),
                    BmsSoh = table.Column<int>(type: "int", nullable: false),
                    BmsStatus = table.Column<int>(type: "int", nullable: false),
                    BmsTemp1Bat = table.Column<double>(type: "float", nullable: false),
                    BmsUsingCap = table.Column<double>(type: "float", nullable: false),
                    BmsVbat = table.Column<double>(type: "float", nullable: false),
                    BmsVdelta = table.Column<double>(type: "float", nullable: false),
                    BmsWarn2 = table.Column<int>(type: "int", nullable: false),
                    BmsWarnCode = table.Column<int>(type: "int", nullable: false),
                    BsystemWorkMode = table.Column<int>(type: "int", nullable: false),
                    Calendar = table.Column<long>(type: "bigint", nullable: false),
                    DataLogSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Day = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DciR = table.Column<double>(type: "float", nullable: false),
                    DciS = table.Column<double>(type: "float", nullable: false),
                    DciT = table.Column<double>(type: "float", nullable: false),
                    DcVoltage = table.Column<double>(type: "float", nullable: false),
                    Debug1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Debug2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeratingMode = table.Column<int>(type: "int", nullable: false),
                    DryContactStatus = table.Column<int>(type: "int", nullable: false),
                    EacChargeToday = table.Column<double>(type: "float", nullable: false),
                    EacChargeTotal = table.Column<double>(type: "float", nullable: false),
                    EacToday = table.Column<double>(type: "float", nullable: false),
                    EacTotal = table.Column<double>(type: "float", nullable: false),
                    EchargeToday = table.Column<double>(type: "float", nullable: false),
                    EchargeTotal = table.Column<double>(type: "float", nullable: false),
                    EdischargeToday = table.Column<double>(type: "float", nullable: false),
                    EdischargeTotal = table.Column<double>(type: "float", nullable: false),
                    Eex1Today = table.Column<double>(type: "float", nullable: false),
                    Eex1Total = table.Column<double>(type: "float", nullable: false),
                    Eex2Today = table.Column<double>(type: "float", nullable: false),
                    Eex2Total = table.Column<double>(type: "float", nullable: false),
                    ElocalLoadToday = table.Column<double>(type: "float", nullable: false),
                    ElocalLoadTotal = table.Column<double>(type: "float", nullable: false),
                    EpsFac = table.Column<double>(type: "float", nullable: false),
                    EpsIac1 = table.Column<double>(type: "float", nullable: false),
                    EpsIac2 = table.Column<double>(type: "float", nullable: false),
                    EpsIac3 = table.Column<double>(type: "float", nullable: false),
                    EpsPac = table.Column<double>(type: "float", nullable: false),
                    EpsPac1 = table.Column<double>(type: "float", nullable: false),
                    EpsPac2 = table.Column<double>(type: "float", nullable: false),
                    EpsPac3 = table.Column<double>(type: "float", nullable: false),
                    EpsPf = table.Column<double>(type: "float", nullable: false),
                    EpsVac1 = table.Column<double>(type: "float", nullable: false),
                    EpsVac2 = table.Column<double>(type: "float", nullable: false),
                    EpsVac3 = table.Column<double>(type: "float", nullable: false),
                    Epv1Today = table.Column<double>(type: "float", nullable: false),
                    Epv1Total = table.Column<double>(type: "float", nullable: false),
                    Epv2Today = table.Column<double>(type: "float", nullable: false),
                    Epv2Total = table.Column<double>(type: "float", nullable: false),
                    Epv3Today = table.Column<double>(type: "float", nullable: false),
                    Epv3Total = table.Column<double>(type: "float", nullable: false),
                    Epv4Today = table.Column<double>(type: "float", nullable: false),
                    Epv4Total = table.Column<double>(type: "float", nullable: false),
                    EpvTotal = table.Column<double>(type: "float", nullable: false),
                    ErrorText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EselfToday = table.Column<double>(type: "float", nullable: false),
                    EselfTotal = table.Column<double>(type: "float", nullable: false),
                    EsystemToday = table.Column<double>(type: "float", nullable: false),
                    EsystemTotal = table.Column<double>(type: "float", nullable: false),
                    EtoGridToday = table.Column<double>(type: "float", nullable: false),
                    EtoGridTotal = table.Column<double>(type: "float", nullable: false),
                    EtoUserToday = table.Column<double>(type: "float", nullable: false),
                    EtoUserTotal = table.Column<double>(type: "float", nullable: false),
                    Fac = table.Column<double>(type: "float", nullable: false),
                    FaultType = table.Column<int>(type: "int", nullable: false),
                    FaultType1 = table.Column<int>(type: "int", nullable: false),
                    Gfci = table.Column<int>(type: "int", nullable: false),
                    Iac1 = table.Column<double>(type: "float", nullable: false),
                    Iac2 = table.Column<double>(type: "float", nullable: false),
                    Iac3 = table.Column<double>(type: "float", nullable: false),
                    Iacr = table.Column<double>(type: "float", nullable: false),
                    InvDelayTime = table.Column<double>(type: "float", nullable: false),
                    Ipv1 = table.Column<double>(type: "float", nullable: false),
                    Ipv2 = table.Column<double>(type: "float", nullable: false),
                    Ipv3 = table.Column<double>(type: "float", nullable: false),
                    Ipv4 = table.Column<double>(type: "float", nullable: false),
                    IsAgain = table.Column<bool>(type: "bit", nullable: false),
                    Iso = table.Column<int>(type: "int", nullable: false),
                    LoadPercent = table.Column<double>(type: "float", nullable: false),
                    Lost = table.Column<bool>(type: "bit", nullable: false),
                    NBusVoltage = table.Column<double>(type: "float", nullable: false),
                    OperatingMode = table.Column<int>(type: "int", nullable: false),
                    OpFullwatt = table.Column<double>(type: "float", nullable: false),
                    Pac = table.Column<double>(type: "float", nullable: false),
                    Pac1 = table.Column<double>(type: "float", nullable: false),
                    Pac2 = table.Column<double>(type: "float", nullable: false),
                    Pac3 = table.Column<double>(type: "float", nullable: false),
                    Pacr = table.Column<double>(type: "float", nullable: false),
                    PacToGridTotal = table.Column<double>(type: "float", nullable: false),
                    PacToLocalLoad = table.Column<double>(type: "float", nullable: false),
                    PacToUserTotal = table.Column<double>(type: "float", nullable: false),
                    PBusVoltage = table.Column<double>(type: "float", nullable: false),
                    Pex1 = table.Column<double>(type: "float", nullable: false),
                    Pex2 = table.Column<double>(type: "float", nullable: false),
                    Pf = table.Column<double>(type: "float", nullable: false),
                    Ppv = table.Column<double>(type: "float", nullable: false),
                    Ppv1 = table.Column<double>(type: "float", nullable: false),
                    Ppv2 = table.Column<double>(type: "float", nullable: false),
                    Ppv3 = table.Column<double>(type: "float", nullable: false),
                    Ppv4 = table.Column<double>(type: "float", nullable: false),
                    Pself = table.Column<double>(type: "float", nullable: false),
                    Psystem = table.Column<double>(type: "float", nullable: false),
                    RealOPPercent = table.Column<int>(type: "int", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    StatusText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SysFaultWord = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord1 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord2 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord3 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord4 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord5 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord6 = table.Column<int>(type: "int", nullable: false),
                    SysFaultWord7 = table.Column<int>(type: "int", nullable: false),
                    Temp1 = table.Column<double>(type: "float", nullable: false),
                    Temp2 = table.Column<double>(type: "float", nullable: false),
                    Temp3 = table.Column<double>(type: "float", nullable: false),
                    Temp4 = table.Column<double>(type: "float", nullable: false),
                    Temp5 = table.Column<double>(type: "float", nullable: false),
                    TimeTotal = table.Column<double>(type: "float", nullable: false),
                    TotalWorkingTime = table.Column<double>(type: "float", nullable: false),
                    TS = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UwSysWorkMode = table.Column<int>(type: "int", nullable: false),
                    Vac1 = table.Column<double>(type: "float", nullable: false),
                    Vac2 = table.Column<double>(type: "float", nullable: false),
                    Vac3 = table.Column<double>(type: "float", nullable: false),
                    Vacr = table.Column<double>(type: "float", nullable: false),
                    VacRs = table.Column<double>(type: "float", nullable: false),
                    VacSt = table.Column<double>(type: "float", nullable: false),
                    VacTr = table.Column<double>(type: "float", nullable: false),
                    Vpv1 = table.Column<double>(type: "float", nullable: false),
                    Vpv2 = table.Column<double>(type: "float", nullable: false),
                    Vpv3 = table.Column<double>(type: "float", nullable: false),
                    Vpv4 = table.Column<double>(type: "float", nullable: false),
                    WarnCode = table.Column<int>(type: "int", nullable: false),
                    WarnCode1 = table.Column<int>(type: "int", nullable: false),
                    WarnText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WithTime = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceMinLastData", x => new { x.SerialNum, x.Time });
                });

            migrationBuilder.CreateTable(
                name: "DeviceNoahInfoData",
                columns: table => new
                {
                    DeviceSn = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Address = table.Column<int>(type: "int", nullable: false),
                    Alias = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AssociatedInvSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BmsVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChargingSocHighLimit = table.Column<int>(type: "int", nullable: false),
                    ChargingSocLowLimit = table.Column<int>(type: "int", nullable: false),
                    ComponentPower = table.Column<double>(type: "float", nullable: false),
                    DatalogSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DefaultPower = table.Column<int>(type: "int", nullable: false),
                    EbmOrderNum = table.Column<int>(type: "int", nullable: false),
                    FwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastUpdateTime = table.Column<long>(type: "bigint", nullable: false),
                    LastUpdateTimeText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Location = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lost = table.Column<bool>(type: "bit", nullable: false),
                    Model = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MpptVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OtaDeviceTypeCodeHigh = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OtaDeviceTypeCodeLow = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PdVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PortName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SmartSocketPower = table.Column<double>(type: "float", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    SysTime = table.Column<long>(type: "bigint", nullable: false),
                    TempType = table.Column<int>(type: "int", nullable: false),
                    Time1Enable = table.Column<int>(type: "int", nullable: false),
                    Time1End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time1Mode = table.Column<int>(type: "int", nullable: false),
                    Time1Power = table.Column<int>(type: "int", nullable: false),
                    Time1Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time2Enable = table.Column<int>(type: "int", nullable: false),
                    Time2End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time2Mode = table.Column<int>(type: "int", nullable: false),
                    Time2Power = table.Column<int>(type: "int", nullable: false),
                    Time2Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time3Enable = table.Column<int>(type: "int", nullable: false),
                    Time3End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time3Mode = table.Column<int>(type: "int", nullable: false),
                    Time3Power = table.Column<int>(type: "int", nullable: false),
                    Time3Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time4Enable = table.Column<int>(type: "int", nullable: false),
                    Time4End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time4Mode = table.Column<int>(type: "int", nullable: false),
                    Time4Power = table.Column<int>(type: "int", nullable: false),
                    Time4Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time5Enable = table.Column<int>(type: "int", nullable: false),
                    Time5End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time5Mode = table.Column<int>(type: "int", nullable: false),
                    Time5Power = table.Column<int>(type: "int", nullable: false),
                    Time5Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time6Enable = table.Column<int>(type: "int", nullable: false),
                    Time6End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time6Mode = table.Column<int>(type: "int", nullable: false),
                    Time6Power = table.Column<int>(type: "int", nullable: false),
                    Time6Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time7Enable = table.Column<int>(type: "int", nullable: false),
                    Time7End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time7Mode = table.Column<int>(type: "int", nullable: false),
                    Time7Power = table.Column<int>(type: "int", nullable: false),
                    Time7Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time8Enable = table.Column<int>(type: "int", nullable: false),
                    Time8End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time8Mode = table.Column<int>(type: "int", nullable: false),
                    Time8Power = table.Column<int>(type: "int", nullable: false),
                    Time8Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time9Enable = table.Column<int>(type: "int", nullable: false),
                    Time9End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time9Mode = table.Column<int>(type: "int", nullable: false),
                    Time9Power = table.Column<int>(type: "int", nullable: false),
                    Time9Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TS = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceNoahInfoData", x => x.DeviceSn);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DeviceMinInfoData");

            migrationBuilder.DropTable(
                name: "DeviceMinLastData");

            migrationBuilder.DropTable(
                name: "DeviceNoahInfoData");

            migrationBuilder.CreateTable(
                name: "DeviceNoahInfo",
                columns: table => new
                {
                    DeviceSn = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Address = table.Column<int>(type: "int", nullable: false),
                    Alias = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AssociatedInvSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BmsVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChargingSocHighLimit = table.Column<int>(type: "int", nullable: false),
                    ChargingSocLowLimit = table.Column<int>(type: "int", nullable: false),
                    ComponentPower = table.Column<double>(type: "float", nullable: false),
                    DatalogSn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DefaultPower = table.Column<int>(type: "int", nullable: false),
                    EbmOrderNum = table.Column<int>(type: "int", nullable: false),
                    FwVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastUpdateTime = table.Column<long>(type: "bigint", nullable: false),
                    LastUpdateTimeText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Location = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lost = table.Column<bool>(type: "bit", nullable: false),
                    Model = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MpptVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OtaDeviceTypeCodeHigh = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OtaDeviceTypeCodeLow = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PdVersion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PortName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SmartSocketPower = table.Column<double>(type: "float", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    SysTime = table.Column<long>(type: "bigint", nullable: false),
                    TS = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    TempType = table.Column<int>(type: "int", nullable: false),
                    Time1Enable = table.Column<int>(type: "int", nullable: false),
                    Time1End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time1Mode = table.Column<int>(type: "int", nullable: false),
                    Time1Power = table.Column<int>(type: "int", nullable: false),
                    Time1Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time2Enable = table.Column<int>(type: "int", nullable: false),
                    Time2End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time2Mode = table.Column<int>(type: "int", nullable: false),
                    Time2Power = table.Column<int>(type: "int", nullable: false),
                    Time2Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time3Enable = table.Column<int>(type: "int", nullable: false),
                    Time3End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time3Mode = table.Column<int>(type: "int", nullable: false),
                    Time3Power = table.Column<int>(type: "int", nullable: false),
                    Time3Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time4Enable = table.Column<int>(type: "int", nullable: false),
                    Time4End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time4Mode = table.Column<int>(type: "int", nullable: false),
                    Time4Power = table.Column<int>(type: "int", nullable: false),
                    Time4Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time5Enable = table.Column<int>(type: "int", nullable: false),
                    Time5End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time5Mode = table.Column<int>(type: "int", nullable: false),
                    Time5Power = table.Column<int>(type: "int", nullable: false),
                    Time5Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time6Enable = table.Column<int>(type: "int", nullable: false),
                    Time6End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time6Mode = table.Column<int>(type: "int", nullable: false),
                    Time6Power = table.Column<int>(type: "int", nullable: false),
                    Time6Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time7Enable = table.Column<int>(type: "int", nullable: false),
                    Time7End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time7Mode = table.Column<int>(type: "int", nullable: false),
                    Time7Power = table.Column<int>(type: "int", nullable: false),
                    Time7Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time8Enable = table.Column<int>(type: "int", nullable: false),
                    Time8End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time8Mode = table.Column<int>(type: "int", nullable: false),
                    Time8Power = table.Column<int>(type: "int", nullable: false),
                    Time8Start = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time9Enable = table.Column<int>(type: "int", nullable: false),
                    Time9End = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Time9Mode = table.Column<int>(type: "int", nullable: false),
                    Time9Power = table.Column<int>(type: "int", nullable: false),
                    Time9Start = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceNoahInfo", x => x.DeviceSn);
                });
        }
    }
}
