// <auto-generated />
using System;
using EnergyAutomate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyAutomate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250413120905_ChangeTable34")]
    partial class ChangeTable34
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceNoahInfoData", b =>
                {
                    b.Property<string>("DeviceSn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociatedInvSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmsVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChargingSocHighLimit")
                        .HasColumnType("int");

                    b.Property<int>("ChargingSocLowLimit")
                        .HasColumnType("int");

                    b.Property<double>("ComponentPower")
                        .HasColumnType("float");

                    b.Property<string>("DatalogSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultPower")
                        .HasColumnType("int");

                    b.Property<int>("EbmOrderNum")
                        .HasColumnType("int");

                    b.Property<string>("FwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastUpdateTime")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateTimeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lost")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MpptVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtaDeviceTypeCodeHigh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtaDeviceTypeCodeLow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SmartSocketPower")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SysTime")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TempType")
                        .HasColumnType("int");

                    b.Property<int>("Time1Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time1End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time1Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time1Power")
                        .HasColumnType("int");

                    b.Property<string>("Time1Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time2Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time2End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time2Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time2Power")
                        .HasColumnType("int");

                    b.Property<string>("Time2Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time3Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time3End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time3Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time3Power")
                        .HasColumnType("int");

                    b.Property<string>("Time3Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time4Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time4End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time4Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time4Power")
                        .HasColumnType("int");

                    b.Property<string>("Time4Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time5Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time5End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time5Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time5Power")
                        .HasColumnType("int");

                    b.Property<string>("Time5Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time6Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time6End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time6Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time6Power")
                        .HasColumnType("int");

                    b.Property<string>("Time6Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time7Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time7End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time7Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time7Power")
                        .HasColumnType("int");

                    b.Property<string>("Time7Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time8Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time8End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time8Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time8Power")
                        .HasColumnType("int");

                    b.Property<string>("Time8Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time9Enable")
                        .HasColumnType("int");

                    b.Property<string>("Time9End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time9Mode")
                        .HasColumnType("int");

                    b.Property<int>("Time9Power")
                        .HasColumnType("int");

                    b.Property<string>("Time9Start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceSn");

                    b.ToTable("GrowattDeviceNoahInfoData");
                });

            modelBuilder.Entity("DeviceNoahLastData", b =>
                {
                    b.Property<string>("deviceSn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("time")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("acCoupleProtectStatus")
                        .HasColumnType("int");

                    b.Property<int>("acCoupleWarnStatus")
                        .HasColumnType("int");

                    b.Property<int>("battery1ProtectStatus")
                        .HasColumnType("int");

                    b.Property<string>("battery1SerialNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("battery1Soc")
                        .HasColumnType("int");

                    b.Property<float>("battery1Temp")
                        .HasColumnType("real");

                    b.Property<float>("battery1TempF")
                        .HasColumnType("real");

                    b.Property<int>("battery1WarnStatus")
                        .HasColumnType("int");

                    b.Property<int>("battery2ProtectStatus")
                        .HasColumnType("int");

                    b.Property<string>("battery2SerialNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("battery2Soc")
                        .HasColumnType("int");

                    b.Property<float>("battery2Temp")
                        .HasColumnType("real");

                    b.Property<float>("battery2TempF")
                        .HasColumnType("real");

                    b.Property<int>("battery2WarnStatus")
                        .HasColumnType("int");

                    b.Property<int>("battery3ProtectStatus")
                        .HasColumnType("int");

                    b.Property<string>("battery3SerialNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("battery3Soc")
                        .HasColumnType("int");

                    b.Property<float>("battery3Temp")
                        .HasColumnType("real");

                    b.Property<float>("battery3TempF")
                        .HasColumnType("real");

                    b.Property<int>("battery3WarnStatus")
                        .HasColumnType("int");

                    b.Property<int>("battery4ProtectStatus")
                        .HasColumnType("int");

                    b.Property<string>("battery4SerialNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("battery4Soc")
                        .HasColumnType("int");

                    b.Property<float>("battery4Temp")
                        .HasColumnType("real");

                    b.Property<float>("battery4TempF")
                        .HasColumnType("real");

                    b.Property<int>("battery4WarnStatus")
                        .HasColumnType("int");

                    b.Property<int>("batteryCycles")
                        .HasColumnType("int");

                    b.Property<int>("batteryPackageQuantity")
                        .HasColumnType("int");

                    b.Property<int>("batterySoh")
                        .HasColumnType("int");

                    b.Property<int>("chargeSocLimit")
                        .HasColumnType("int");

                    b.Property<int>("ctFlag")
                        .HasColumnType("int");

                    b.Property<float>("ctSelfPower")
                        .HasColumnType("real");

                    b.Property<string>("datalogSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dischargeSocLimit")
                        .HasColumnType("int");

                    b.Property<float>("eacMonth")
                        .HasColumnType("real");

                    b.Property<float>("eacToday")
                        .HasColumnType("real");

                    b.Property<float>("eacTotal")
                        .HasColumnType("real");

                    b.Property<float>("eacYear")
                        .HasColumnType("real");

                    b.Property<int>("faultStatus")
                        .HasColumnType("int");

                    b.Property<int>("heatingStatus")
                        .HasColumnType("int");

                    b.Property<float>("householdLoadApartFromGroplug")
                        .HasColumnType("real");

                    b.Property<int>("isAgain")
                        .HasColumnType("int");

                    b.Property<float>("maxCellVoltage")
                        .HasColumnType("real");

                    b.Property<float>("minCellVoltage")
                        .HasColumnType("real");

                    b.Property<int>("mpptProtectStatus")
                        .HasColumnType("int");

                    b.Property<int>("onOffGrid")
                        .HasColumnType("int");

                    b.Property<float>("pac")
                        .HasColumnType("real");

                    b.Property<int>("pdWarnStatus")
                        .HasColumnType("int");

                    b.Property<float>("ppv")
                        .HasColumnType("real");

                    b.Property<float>("pv1Current")
                        .HasColumnType("real");

                    b.Property<float>("pv1Temp")
                        .HasColumnType("real");

                    b.Property<float>("pv1Voltage")
                        .HasColumnType("real");

                    b.Property<float>("pv2Current")
                        .HasColumnType("real");

                    b.Property<float>("pv2Temp")
                        .HasColumnType("real");

                    b.Property<float>("pv2Voltage")
                        .HasColumnType("real");

                    b.Property<float>("pv3Current")
                        .HasColumnType("real");

                    b.Property<float>("pv3Temp")
                        .HasColumnType("real");

                    b.Property<float>("pv3Voltage")
                        .HasColumnType("real");

                    b.Property<float>("pv4Current")
                        .HasColumnType("real");

                    b.Property<float>("pv4Temp")
                        .HasColumnType("real");

                    b.Property<float>("pv4Voltage")
                        .HasColumnType("real");

                    b.Property<int>("settableTimePeriod")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<float>("systemTemp")
                        .HasColumnType("real");

                    b.Property<string>("timeStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalBatteryPackChargingPower")
                        .HasColumnType("int");

                    b.Property<int>("totalBatteryPackChargingStatus")
                        .HasColumnType("int");

                    b.Property<int>("totalBatteryPackSoc")
                        .HasColumnType("int");

                    b.Property<float>("totalHouseholdLoad")
                        .HasColumnType("real");

                    b.Property<int>("workMode")
                        .HasColumnType("int");

                    b.HasKey("deviceSn", "time");

                    b.ToTable("GrowattDeviceNoahLastData");
                });

            modelBuilder.Entity("EnergyAutomate.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EnergyAutomate.Definitions.GrowattElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ElementType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrowattElements");
                });

            modelBuilder.Entity("EnergyAutomate.Growatt.DeviceList", b =>
                {
                    b.Property<string>("DeviceSn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBatteryEmpty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBatteryFull")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("IsOfflineSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PowerValueCommited")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PowerValueLastChanged")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PowerValueRequested")
                        .HasColumnType("int");

                    b.Property<int>("Soc")
                        .HasColumnType("int");

                    b.Property<int>("SocMin")
                        .HasColumnType("int");

                    b.HasKey("DeviceSn");

                    b.ToTable("GrowattDevices");
                });

            modelBuilder.Entity("EnergyAutomate.Growatt.DeviceMinInfoData", b =>
                {
                    b.Property<string>("serialNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("addr")
                        .HasColumnType("int");

                    b.Property<string>("alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bagingTestStep")
                        .HasColumnType("int");

                    b.Property<int>("batParallelNum")
                        .HasColumnType("int");

                    b.Property<int>("batSeriesNum")
                        .HasColumnType("int");

                    b.Property<double>("batTempLowerLimitC")
                        .HasColumnType("float");

                    b.Property<double>("batTempLowerLimitD")
                        .HasColumnType("float");

                    b.Property<double>("batTempUpperLimitC")
                        .HasColumnType("float");

                    b.Property<double>("batTempUpperLimitD")
                        .HasColumnType("float");

                    b.Property<int>("batteryType")
                        .HasColumnType("int");

                    b.Property<int>("bctAdjust")
                        .HasColumnType("int");

                    b.Property<int>("bctMode")
                        .HasColumnType("int");

                    b.Property<string>("bdc1Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bdc1Sn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bdc1Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bdcAuthversion")
                        .HasColumnType("int");

                    b.Property<int>("bdcMode")
                        .HasColumnType("int");

                    b.Property<int>("bmsCommunicationType")
                        .HasColumnType("int");

                    b.Property<string>("bmsSoftwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("comAddress")
                        .HasColumnType("int");

                    b.Property<string>("communicationVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("countrySelected")
                        .HasColumnType("int");

                    b.Property<string>("dataLogSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deviceType")
                        .HasColumnType("int");

                    b.Property<int>("dtc")
                        .HasColumnType("int");

                    b.Property<double>("eToday")
                        .HasColumnType("float");

                    b.Property<double>("eTotal")
                        .HasColumnType("float");

                    b.Property<double>("energyMonth")
                        .HasColumnType("float");

                    b.Property<string>("energyMonthText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("hwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("imgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("innerVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("lastUpdateTime")
                        .HasColumnType("bigint");

                    b.Property<string>("lastUpdateTimeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<string>("liBatteryFwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("liBatteryManufacturers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("lost")
                        .HasColumnType("bit");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("modbusVersion")
                        .HasColumnType("int");

                    b.Property<long>("model")
                        .HasColumnType("bigint");

                    b.Property<string>("modelText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monitorVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("mppt")
                        .HasColumnType("float");

                    b.Property<double>("pCharge")
                        .HasColumnType("float");

                    b.Property<double>("pDischarge")
                        .HasColumnType("float");

                    b.Property<string>("parentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plantId")
                        .HasColumnType("int");

                    b.Property<string>("plantname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pmax")
                        .HasColumnType("int");

                    b.Property<string>("portName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("power")
                        .HasColumnType("float");

                    b.Property<string>("powerMaxText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priorityChoose")
                        .HasColumnType("int");

                    b.Property<int>("restartTime")
                        .HasColumnType("int");

                    b.Property<int>("startTime")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("statusText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("strNum")
                        .HasColumnType("int");

                    b.Property<string>("sysTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tcpServerIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("timezone")
                        .HasColumnType("float");

                    b.Property<int>("trakerModel")
                        .HasColumnType("int");

                    b.Property<string>("treeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("treeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("updating")
                        .HasColumnType("bit");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("vbatStartForDischarge")
                        .HasColumnType("float");

                    b.Property<double>("vbatStopForCharge")
                        .HasColumnType("float");

                    b.Property<double>("vbatStopForDischarge")
                        .HasColumnType("float");

                    b.Property<double>("vbatWarnClr")
                        .HasColumnType("float");

                    b.Property<double>("vbatWarning")
                        .HasColumnType("float");

                    b.Property<double>("vnormal")
                        .HasColumnType("float");

                    b.Property<int>("vppOpen")
                        .HasColumnType("int");

                    b.Property<int>("wselectBaudrate")
                        .HasColumnType("int");

                    b.HasKey("serialNum");

                    b.ToTable("GrowattDeviceMinInfoData");
                });

            modelBuilder.Entity("EnergyAutomate.Growatt.DeviceMinLastData", b =>
                {
                    b.Property<string>("SerialNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<bool>("Again")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BMerterConnectFlag")
                        .HasColumnType("int");

                    b.Property<string>("BatSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteryNo")
                        .HasColumnType("int");

                    b.Property<string>("BatterySN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Bdc1ChargePower")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1ChargeTotal")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1DischargePower")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1DischargeTotal")
                        .HasColumnType("float");

                    b.Property<int>("Bdc1FaultType")
                        .HasColumnType("int");

                    b.Property<double>("Bdc1Ibat")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Ibb")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Illc")
                        .HasColumnType("float");

                    b.Property<int>("Bdc1Mode")
                        .HasColumnType("int");

                    b.Property<int>("Bdc1Soc")
                        .HasColumnType("int");

                    b.Property<int>("Bdc1Status")
                        .HasColumnType("int");

                    b.Property<double>("Bdc1Temp1")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Temp2")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Vbat")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Vbus1")
                        .HasColumnType("float");

                    b.Property<double>("Bdc1Vbus2")
                        .HasColumnType("float");

                    b.Property<int>("Bdc1WarnCode")
                        .HasColumnType("int");

                    b.Property<double>("Bdc2ChargePower")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2ChargeTotal")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2DischargePower")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2DischargeTotal")
                        .HasColumnType("float");

                    b.Property<int>("Bdc2FaultType")
                        .HasColumnType("int");

                    b.Property<double>("Bdc2Ibat")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Ibb")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Illc")
                        .HasColumnType("float");

                    b.Property<int>("Bdc2Mode")
                        .HasColumnType("int");

                    b.Property<int>("Bdc2Soc")
                        .HasColumnType("int");

                    b.Property<int>("Bdc2Status")
                        .HasColumnType("int");

                    b.Property<double>("Bdc2Temp1")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Temp2")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Vbat")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Vbus1")
                        .HasColumnType("float");

                    b.Property<double>("Bdc2Vbus2")
                        .HasColumnType("float");

                    b.Property<int>("Bdc2WarnCode")
                        .HasColumnType("int");

                    b.Property<int>("BdcBusRef")
                        .HasColumnType("int");

                    b.Property<int>("BdcDerateReason")
                        .HasColumnType("int");

                    b.Property<int>("BdcFaultSubCode")
                        .HasColumnType("int");

                    b.Property<int>("BdcStatus")
                        .HasColumnType("int");

                    b.Property<double>("BdcVbus2Neg")
                        .HasColumnType("float");

                    b.Property<int>("BdcWarnSubCode")
                        .HasColumnType("int");

                    b.Property<int>("BgridType")
                        .HasColumnType("int");

                    b.Property<int>("BmsCommunicationType")
                        .HasColumnType("int");

                    b.Property<double>("BmsCvVolt")
                        .HasColumnType("float");

                    b.Property<int>("BmsError2")
                        .HasColumnType("int");

                    b.Property<int>("BmsError3")
                        .HasColumnType("int");

                    b.Property<int>("BmsError4")
                        .HasColumnType("int");

                    b.Property<int>("BmsFaultType")
                        .HasColumnType("int");

                    b.Property<string>("BmsFwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BmsIbat")
                        .HasColumnType("float");

                    b.Property<int>("BmsIcycle")
                        .HasColumnType("int");

                    b.Property<double>("BmsInfo")
                        .HasColumnType("float");

                    b.Property<int>("BmsIosStatus")
                        .HasColumnType("int");

                    b.Property<double>("BmsMaxCurr")
                        .HasColumnType("float");

                    b.Property<string>("BmsMcuVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BmsPackInfo")
                        .HasColumnType("float");

                    b.Property<int>("BmsSoc")
                        .HasColumnType("int");

                    b.Property<int>("BmsSoh")
                        .HasColumnType("int");

                    b.Property<int>("BmsStatus")
                        .HasColumnType("int");

                    b.Property<double>("BmsTemp1Bat")
                        .HasColumnType("float");

                    b.Property<double>("BmsUsingCap")
                        .HasColumnType("float");

                    b.Property<double>("BmsVbat")
                        .HasColumnType("float");

                    b.Property<double>("BmsVdelta")
                        .HasColumnType("float");

                    b.Property<int>("BmsWarn2")
                        .HasColumnType("int");

                    b.Property<int>("BmsWarnCode")
                        .HasColumnType("int");

                    b.Property<int>("BsystemWorkMode")
                        .HasColumnType("int");

                    b.Property<long>("Calendar")
                        .HasColumnType("bigint");

                    b.Property<string>("DataLogSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DcVoltage")
                        .HasColumnType("float");

                    b.Property<double>("DciR")
                        .HasColumnType("float");

                    b.Property<double>("DciS")
                        .HasColumnType("float");

                    b.Property<double>("DciT")
                        .HasColumnType("float");

                    b.Property<string>("Debug1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Debug2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeratingMode")
                        .HasColumnType("int");

                    b.Property<int>("DryContactStatus")
                        .HasColumnType("int");

                    b.Property<double>("EacChargeToday")
                        .HasColumnType("float");

                    b.Property<double>("EacChargeTotal")
                        .HasColumnType("float");

                    b.Property<double>("EacToday")
                        .HasColumnType("float");

                    b.Property<double>("EacTotal")
                        .HasColumnType("float");

                    b.Property<double>("EchargeToday")
                        .HasColumnType("float");

                    b.Property<double>("EchargeTotal")
                        .HasColumnType("float");

                    b.Property<double>("EdischargeToday")
                        .HasColumnType("float");

                    b.Property<double>("EdischargeTotal")
                        .HasColumnType("float");

                    b.Property<double>("Eex1Today")
                        .HasColumnType("float");

                    b.Property<double>("Eex1Total")
                        .HasColumnType("float");

                    b.Property<double>("Eex2Today")
                        .HasColumnType("float");

                    b.Property<double>("Eex2Total")
                        .HasColumnType("float");

                    b.Property<double>("ElocalLoadToday")
                        .HasColumnType("float");

                    b.Property<double>("ElocalLoadTotal")
                        .HasColumnType("float");

                    b.Property<double>("EpsFac")
                        .HasColumnType("float");

                    b.Property<double>("EpsIac1")
                        .HasColumnType("float");

                    b.Property<double>("EpsIac2")
                        .HasColumnType("float");

                    b.Property<double>("EpsIac3")
                        .HasColumnType("float");

                    b.Property<double>("EpsPac")
                        .HasColumnType("float");

                    b.Property<double>("EpsPac1")
                        .HasColumnType("float");

                    b.Property<double>("EpsPac2")
                        .HasColumnType("float");

                    b.Property<double>("EpsPac3")
                        .HasColumnType("float");

                    b.Property<double>("EpsPf")
                        .HasColumnType("float");

                    b.Property<double>("EpsVac1")
                        .HasColumnType("float");

                    b.Property<double>("EpsVac2")
                        .HasColumnType("float");

                    b.Property<double>("EpsVac3")
                        .HasColumnType("float");

                    b.Property<double>("Epv1Today")
                        .HasColumnType("float");

                    b.Property<double>("Epv1Total")
                        .HasColumnType("float");

                    b.Property<double>("Epv2Today")
                        .HasColumnType("float");

                    b.Property<double>("Epv2Total")
                        .HasColumnType("float");

                    b.Property<double>("Epv3Today")
                        .HasColumnType("float");

                    b.Property<double>("Epv3Total")
                        .HasColumnType("float");

                    b.Property<double>("Epv4Today")
                        .HasColumnType("float");

                    b.Property<double>("Epv4Total")
                        .HasColumnType("float");

                    b.Property<double>("EpvTotal")
                        .HasColumnType("float");

                    b.Property<string>("ErrorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EselfToday")
                        .HasColumnType("float");

                    b.Property<double>("EselfTotal")
                        .HasColumnType("float");

                    b.Property<double>("EsystemToday")
                        .HasColumnType("float");

                    b.Property<double>("EsystemTotal")
                        .HasColumnType("float");

                    b.Property<double>("EtoGridToday")
                        .HasColumnType("float");

                    b.Property<double>("EtoGridTotal")
                        .HasColumnType("float");

                    b.Property<double>("EtoUserToday")
                        .HasColumnType("float");

                    b.Property<double>("EtoUserTotal")
                        .HasColumnType("float");

                    b.Property<double>("Fac")
                        .HasColumnType("float");

                    b.Property<int>("FaultType")
                        .HasColumnType("int");

                    b.Property<int>("FaultType1")
                        .HasColumnType("int");

                    b.Property<int>("Gfci")
                        .HasColumnType("int");

                    b.Property<double>("Iac1")
                        .HasColumnType("float");

                    b.Property<double>("Iac2")
                        .HasColumnType("float");

                    b.Property<double>("Iac3")
                        .HasColumnType("float");

                    b.Property<double>("Iacr")
                        .HasColumnType("float");

                    b.Property<double>("InvDelayTime")
                        .HasColumnType("float");

                    b.Property<double>("Ipv1")
                        .HasColumnType("float");

                    b.Property<double>("Ipv2")
                        .HasColumnType("float");

                    b.Property<double>("Ipv3")
                        .HasColumnType("float");

                    b.Property<double>("Ipv4")
                        .HasColumnType("float");

                    b.Property<bool>("IsAgain")
                        .HasColumnType("bit");

                    b.Property<int>("Iso")
                        .HasColumnType("int");

                    b.Property<double>("LoadPercent")
                        .HasColumnType("float");

                    b.Property<bool>("Lost")
                        .HasColumnType("bit");

                    b.Property<double>("NBusVoltage")
                        .HasColumnType("float");

                    b.Property<double>("OpFullwatt")
                        .HasColumnType("float");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("int");

                    b.Property<double>("PBusVoltage")
                        .HasColumnType("float");

                    b.Property<double>("Pac")
                        .HasColumnType("float");

                    b.Property<double>("Pac1")
                        .HasColumnType("float");

                    b.Property<double>("Pac2")
                        .HasColumnType("float");

                    b.Property<double>("Pac3")
                        .HasColumnType("float");

                    b.Property<double>("PacToGridTotal")
                        .HasColumnType("float");

                    b.Property<double>("PacToLocalLoad")
                        .HasColumnType("float");

                    b.Property<double>("PacToUserTotal")
                        .HasColumnType("float");

                    b.Property<double>("Pacr")
                        .HasColumnType("float");

                    b.Property<double>("Pex1")
                        .HasColumnType("float");

                    b.Property<double>("Pex2")
                        .HasColumnType("float");

                    b.Property<double>("Pf")
                        .HasColumnType("float");

                    b.Property<double>("Ppv")
                        .HasColumnType("float");

                    b.Property<double>("Ppv1")
                        .HasColumnType("float");

                    b.Property<double>("Ppv2")
                        .HasColumnType("float");

                    b.Property<double>("Ppv3")
                        .HasColumnType("float");

                    b.Property<double>("Ppv4")
                        .HasColumnType("float");

                    b.Property<double>("Pself")
                        .HasColumnType("float");

                    b.Property<double>("Psystem")
                        .HasColumnType("float");

                    b.Property<int>("RealOPPercent")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SysFaultWord")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord1")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord2")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord3")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord4")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord5")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord6")
                        .HasColumnType("int");

                    b.Property<int>("SysFaultWord7")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Temp1")
                        .HasColumnType("float");

                    b.Property<double>("Temp2")
                        .HasColumnType("float");

                    b.Property<double>("Temp3")
                        .HasColumnType("float");

                    b.Property<double>("Temp4")
                        .HasColumnType("float");

                    b.Property<double>("Temp5")
                        .HasColumnType("float");

                    b.Property<double>("TimeTotal")
                        .HasColumnType("float");

                    b.Property<double>("TotalWorkingTime")
                        .HasColumnType("float");

                    b.Property<int>("UwSysWorkMode")
                        .HasColumnType("int");

                    b.Property<double>("Vac1")
                        .HasColumnType("float");

                    b.Property<double>("Vac2")
                        .HasColumnType("float");

                    b.Property<double>("Vac3")
                        .HasColumnType("float");

                    b.Property<double>("VacRs")
                        .HasColumnType("float");

                    b.Property<double>("VacSt")
                        .HasColumnType("float");

                    b.Property<double>("VacTr")
                        .HasColumnType("float");

                    b.Property<double>("Vacr")
                        .HasColumnType("float");

                    b.Property<double>("Vpv1")
                        .HasColumnType("float");

                    b.Property<double>("Vpv2")
                        .HasColumnType("float");

                    b.Property<double>("Vpv3")
                        .HasColumnType("float");

                    b.Property<double>("Vpv4")
                        .HasColumnType("float");

                    b.Property<int>("WarnCode")
                        .HasColumnType("int");

                    b.Property<int>("WarnCode1")
                        .HasColumnType("int");

                    b.Property<string>("WarnText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WithTime")
                        .HasColumnType("bit");

                    b.HasKey("SerialNum", "Time");

                    b.ToTable("GrowattDeviceMinLastData");
                });

            modelBuilder.Entity("EnergyAutomate.Tibber.TibberPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoModeRestriction")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TibberPrices");
                });

            modelBuilder.Entity("EnergyAutomate.Tibber.TibberRealTimeMeasurement", b =>
                {
                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("AccumulatedConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccumulatedConsumptionLastHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AccumulatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccumulatedProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccumulatedProductionLastHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AccumulatedReward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AveragePower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentPhase1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentPhase2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentPhase3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LastMeterConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LastMeterProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxPower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxPowerProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinPowerProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PowerAvgConsumption")
                        .HasColumnType("int");

                    b.Property<int>("PowerAvgProduction")
                        .HasColumnType("int");

                    b.Property<decimal?>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PowerProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PowerProductionReactive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PowerReactive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PowerValueNewCommited")
                        .HasColumnType("int");

                    b.Property<string>("PowerValueNewDeviceSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PowerValueNewRequested")
                        .HasColumnType("int");

                    b.Property<int>("PowerValueTotalCommited")
                        .HasColumnType("int");

                    b.Property<int>("PowerValueTotalDefault")
                        .HasColumnType("int");

                    b.Property<int>("PowerValueTotalRequested")
                        .HasColumnType("int");

                    b.Property<bool>("SettingAutoMode")
                        .HasColumnType("bit");

                    b.Property<int>("SettingAvgPowerHysteresis")
                        .HasColumnType("int");

                    b.Property<bool>("SettingBatteryPriorityMode")
                        .HasColumnType("bit");

                    b.Property<int>("SettingOffSetAvg")
                        .HasColumnType("int");

                    b.Property<int>("SettingPowerLoadSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("SettingRestrictionMode")
                        .HasColumnType("bit");

                    b.Property<bool>("SettingRestrictionState")
                        .HasColumnType("bit");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("VoltagePhase1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VoltagePhase2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VoltagePhase3")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TS");

                    b.ToTable("TibberRealTimeMeasurements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EnergyAutomate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EnergyAutomate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyAutomate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EnergyAutomate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
