using Newtonsoft.Json;

namespace Growatt.Sdk
{

    public class DeviceMinInfoData
    {
        public double vPidPvcpe { get; set; }
        public double realOPPercent { get; set; }
        public int warnCode { get; set; }
        public double epv5Today { get; set; }
        public double pacr { get; set; }
        public double epv13Today { get; set; }
        public double pacs { get; set; }
        public double rac { get; set; }
        public double epv13Total { get; set; }
        public double pact { get; set; }
        public double epvTotal { get; set; }
        public double pBusVoltage { get; set; }
        public int deratingMode { get; set; }
        public double epv5Total { get; set; }
        public string debug3 { get; set; }
        public double vString8 { get; set; }
        public double vString7 { get; set; }
        public double vString9 { get; set; }
        public int pidStatus { get; set; }
        public double iPidPvepe { get; set; }
        public double vString2 { get; set; }
        public int dwStringWarningValue1 { get; set; }
        public double vString1 { get; set; }
        public double vString4 { get; set; }
        public string pidStatusText { get; set; }
        public double vString3 { get; set; }
        public double vString6 { get; set; }
        public double vString5 { get; set; }
        public double reactPowerMax { get; set; }
        public double epv11Today { get; set; }
        public double vPidPvbpe { get; set; }
        public double nBusVoltage { get; set; }
        public double ppv2 { get; set; }
        public double ppv3 { get; set; }
        public double ppv4 { get; set; }
        public double ppv5 { get; set; }
        public double compqt { get; set; }
        public double compqs { get; set; }
        public double epv11Total { get; set; }
        public double compqr { get; set; }
        public double ppv1 { get; set; }
        public double temperature { get; set; }
        public string debug1 { get; set; }
        public string debug2 { get; set; }
        public DeviceMinInfoCalendar calendar { get; set; }
        public double sDci { get; set; }
        public int address { get; set; }
        public double epv7Today { get; set; }
        public double epv1Today { get; set; }
        public double epv7Total { get; set; }
        public double epv1Total { get; set; }
        public double vact { get; set; }
        public double vacs { get; set; }
        public double vacr { get; set; }
        public double iPidPvdpe { get; set; }
        public double ppv { get; set; }
        public double wPIDFaultValue { get; set; }
        public double ctqt { get; set; }
        public double ctqr { get; set; }
        public string dataLogSn { get; set; }
        public double ctqs { get; set; }
        public double vpv3 { get; set; }
        public double vpv2 { get; set; }
        public double vpv1 { get; set; }
        public double tDci { get; set; }
        public double vPidPvepe { get; set; }
        public int apfStatus { get; set; }
        public double vpv9 { get; set; }
        public double vpv8 { get; set; }
        public double vpv7 { get; set; }
        public double vpv6 { get; set; }
        public double vpv5 { get; set; }
        public double vpv4 { get; set; }
        public double vpv16 { get; set; }
        public double pac { get; set; }
        public double vpv15 { get; set; }
        public double powerTotal { get; set; }
        public double powerToday { get; set; }
        public int pidFaultCode { get; set; }
        public double vString32 { get; set; }
        public double vString31 { get; set; }
        public double vString30 { get; set; }
        public double vpv10 { get; set; }
        public double vpv14 { get; set; }
        public double vpv13 { get; set; }
        public double vpv12 { get; set; }
        public double vpv11 { get; set; }
        public double iPidPvcpe { get; set; }
        public double ppv6 { get; set; }
        public double ppv7 { get; set; }
        public double ppv8 { get; set; }
        public double ppv9 { get; set; }
        public double epv3Total { get; set; }
        public double epv3Today { get; set; }
        public double vPidPvdpe { get; set; }
        public double vString22 { get; set; }
        public double vString21 { get; set; }
        public double vString20 { get; set; }
        public double vString26 { get; set; }
        public double epv9Today { get; set; }
        public double vString25 { get; set; }
        public double vPidPvpe15 { get; set; }
        public double vString24 { get; set; }
        public double vPidPvpe16 { get; set; }
        public double vString23 { get; set; }
        public double epv9Total { get; set; }
        public double vPidPvpe13 { get; set; }
        public double vPidPvpe14 { get; set; }
        public double vString29 { get; set; }
        public double vPidPvpe11 { get; set; }
        public double vString28 { get; set; }
        public double vPidPvpe12 { get; set; }
        public double vString27 { get; set; }
        public int afciStatus { get; set; }
        public double epv8Today { get; set; }
        public double epv8Total { get; set; }
        public double vPidPvpe10 { get; set; }
        public double epv2Today { get; set; }
        public double epv2Total { get; set; }
        public double iPidPvpe13 { get; set; }
        public double iPidPvpe12 { get; set; }
        public double iPidPvpe11 { get; set; }
        public double iPidPvpe10 { get; set; }
        public double iPidPvpe16 { get; set; }
        public DeviceMinInfoCalendar timeCalendar { get; set; }
        public double iPidPvpe15 { get; set; }
        public double iPidPvpe14 { get; set; }
        public double vString11 { get; set; }
        public double vString10 { get; set; }
        public bool again { get; set; }
        public double vString15 { get; set; }
        public double vString14 { get; set; }
        public double vString13 { get; set; }
        public double eacTotal { get; set; }
        public double vString12 { get; set; }
        public double eacToday { get; set; }
        public double vString19 { get; set; }
        public double vString18 { get; set; }
        public double vString17 { get; set; }
        public double iPidPvbpe { get; set; }
        public double vString16 { get; set; }
        public int faultCode2 { get; set; }
        public int faultCode1 { get; set; }
        public double epv12Total { get; set; }
        public string statusText { get; set; }
        public double epv12Today { get; set; }
        public string time { get; set; }
        public double pvIso { get; set; }
        public double epv14Total { get; set; }
        public double epv6Total { get; set; }
        public double epv14Today { get; set; }
        public double fac { get; set; }
        public double epv6Today { get; set; }
        public bool lost { get; set; }
        public double vacTr { get; set; }
        public int id { get; set; }
        public string serialNum { get; set; }
        public double wStringStatusValue { get; set; }
        public double temperature5 { get; set; }
        public double epv16Total { get; set; }
        public double temperature4 { get; set; }
        public double epv16Today { get; set; }
        public double iPidPvape { get; set; }
        public double eRacToday { get; set; }
        public double eRacTotal { get; set; }
        public double vacSt { get; set; }
        public double vPidPvgpe { get; set; }
        public int status { get; set; }
        public double ppv15 { get; set; }
        public double ppv16 { get; set; }
        public double ppv13 { get; set; }
        public double ppv14 { get; set; }
        public double ppv11 { get; set; }
        public double ppv12 { get; set; }
        public double ppv10 { get; set; }
        public double strUnblance { get; set; }
        public double afciPv1 { get; set; }
        public double afciPv2 { get; set; }
        public double ctharis { get; set; }
        public double ctharit { get; set; }
        public double ctharir { get; set; }
        public double temperature3 { get; set; }
        public double epv10Today { get; set; }
        public double temperature2 { get; set; }
        public double epv10Total { get; set; }
        public double reactPower { get; set; }
        public bool withTime { get; set; }
        public double ipv16 { get; set; }
        public double epv4Total { get; set; }
        public double epv4Today { get; set; }
        public double ipv12 { get; set; }
        public double ipv13 { get; set; }
        public double ipv14 { get; set; }
        public double ipv15 { get; set; }
        public double ctit { get; set; }
        public double ipv10 { get; set; }
        public double ipv11 { get; set; }
        public object maxBean { get; set; }
        public double vPidPvpe9 { get; set; }
        public double ctir { get; set; }
        public double iPidPvhpe { get; set; }
        public double ctis { get; set; }
        public double faultValue { get; set; }
        public double vPidPvfpe { get; set; }
        public double strFault { get; set; }
        public double vPidPvape { get; set; }
        public double currentString32 { get; set; }
        public double currentString31 { get; set; }
        public double currentString30 { get; set; }
        public double currentString1 { get; set; }
        public double strBreak { get; set; }
        public double currentString5 { get; set; }
        public double currentString4 { get; set; }
        public double currentString3 { get; set; }
        public double currentString2 { get; set; }
        public double currentString9 { get; set; }
        public double currentString8 { get; set; }
        public string day { get; set; }
        public double currentString7 { get; set; }
        public double currentString6 { get; set; }
        public string apfStatusText { get; set; }
        public double warnBit { get; set; }
        public double reactPowerTotal { get; set; }
        public double gfci { get; set; }
        public double iPidPvgpe { get; set; }
        public double iacr { get; set; }
        public double iact { get; set; }
        public double iacs { get; set; }
        public double currentString16 { get; set; }
        public double warningValue2 { get; set; }
        public double currentString15 { get; set; }
        public double strUnmatch { get; set; }
        public double warningValue1 { get; set; }
        public double currentString14 { get; set; }
        public double currentString13 { get; set; }
        public double warningValue3 { get; set; }
        public double currentString12 { get; set; }
        public double currentString11 { get; set; }
        public double currentString10 { get; set; }
        public double rDci { get; set; }
        public double ipv2 { get; set; }
        public double opFullwatt { get; set; }
        public double ipv1 { get; set; }
        public double ipv4 { get; set; }
        public double ipv3 { get; set; }
        public double vacRs { get; set; }
        public double ipv6 { get; set; }
        public double ipv5 { get; set; }
        public double ipv8 { get; set; }
        public string alias { get; set; }
        public double faultType { get; set; }
        public double ipv7 { get; set; }
        public double ipv9 { get; set; }
        public double currentString19 { get; set; }
        public double currentString18 { get; set; }
        public double currentString17 { get; set; }
        public double currentString27 { get; set; }
        public double currentString26 { get; set; }
        public double pidBus { get; set; }
        public double currentString25 { get; set; }
        public double currentString24 { get; set; }
        public double currentString23 { get; set; }
        public double currentString22 { get; set; }
        public double timeTotal { get; set; }
        public double currentString21 { get; set; }
        public double currentString20 { get; set; }
        public double ipmTemperature { get; set; }
        public double compharis { get; set; }
        public double iPidPvfpe { get; set; }
        public double compharit { get; set; }
        public double compharir { get; set; }
        public double pf { get; set; }
        public double epv15Today { get; set; }
        public double vPidPvhpe { get; set; }
        public double iPidPvpe9 { get; set; }
        public double currentString29 { get; set; }
        public double currentString28 { get; set; }
        public double epv15Total { get; set; }

        [JsonIgnore]
        public DateTimeOffset TS { get; set; }
    }
}