using Newtonsoft.Json;

namespace EnergyAutomate.Growatt
{
    public class DeviceNoahHistoricalData
    {
        #region Properties

        public bool Again { get; set; }
        public double BatPower { get; set; }
        public double BmsBatteryCurr { get; set; }
        public double BmsBatteryTemp { get; set; }
        public double BmsBatteryVolt { get; set; }
        public double BmsConstantVolt { get; set; }
        public int BmsSOC { get; set; }
        public int BmsSOH { get; set; }
        public int BmsUsingCap { get; set; }
        public long Calendar { get; set; }
        public int ChipType { get; set; }
        public string DataLogSn { get; set; }
        public string DayMap { get; set; }
        public double DcTemp { get; set; }
        public int DeviceType { get; set; }
        public double EacToday { get; set; }
        public double EacTotal { get; set; }
        public double Echarge1Today { get; set; }
        public double Echarge1Total { get; set; }
        public double Edischarge1Today { get; set; }
        public double Edischarge1Total { get; set; }
        public double ElocalLoadHour { get; set; }
        public double ElocalLoadMonth { get; set; }
        public double ElocalLoadToday { get; set; }
        public double ElocalLoadTotal { get; set; }
        public double ElocalLoadYear { get; set; }
        public double EpsIac1 { get; set; }
        public double EpsIac2 { get; set; }
        public double EpsVac2 { get; set; }
        public double Epv1Today { get; set; }
        public double Epv1Total { get; set; }
        public double Epv2Today { get; set; }
        public double Epv2Total { get; set; }
        public double Epv3Today { get; set; }
        public double Epv3Total { get; set; }
        public double EpvHour { get; set; }
        public double EpvMonth { get; set; }
        public double EpvToday { get; set; }
        public double EpvTotal { get; set; }
        public double EpvYear { get; set; }
        public string ErrorText { get; set; }
        public double EselfHour { get; set; }
        public double EselfMonth { get; set; }
        public double Eselftoday { get; set; }
        public double Eselftotal { get; set; }
        public double EselfYear { get; set; }
        public double EsystemHour { get; set; }
        public double EsystemMonth { get; set; }
        public double Esystemtoday { get; set; }
        public double Esystemtotal { get; set; }
        public double EsystemYear { get; set; }
        public double EToGridHour { get; set; }
        public double EToGridMonth { get; set; }
        public double EtoGridToday { get; set; }
        public double EtoGridTotal { get; set; }
        public double EToGridYear { get; set; }
        public double EToUserHour { get; set; }
        public double EToUserMonth { get; set; }
        public double EtoUserToday { get; set; }
        public double EtoUserTotal { get; set; }
        public double EToUserYear { get; set; }
        public double Fac { get; set; }
        public int FaultBitCode { get; set; }
        public int FaultCode { get; set; }
        public double GenCurr { get; set; }
        public double GenEnergy { get; set; }
        public double GenEnergyToday { get; set; }
        public double GenFreq { get; set; }
        public double GenPower { get; set; }
        public double GenVol { get; set; }
        public int GridStatus { get; set; }
        public string HmiVersion { get; set; }
        public double Iac1 { get; set; }
        public double Iac2 { get; set; }
        public double Ibat { get; set; }
        public double InvTemp { get; set; }
        public double Ipv1 { get; set; }
        public double Ipv2 { get; set; }
        public double Ipv3 { get; set; }
        public double LoadPower1 { get; set; }
        public double LoadPower2 { get; set; }
        public bool Lost { get; set; }
        public string M1Version { get; set; }
        public string M2Version { get; set; }
        public double Pac { get; set; }
        public double Pac1 { get; set; }
        public double Pac2 { get; set; }
        public double PacToGridR { get; set; }
        public double PacToGridS { get; set; }
        public double PacToGridTotal { get; set; }
        public double PacToUserR { get; set; }
        public double PacToUserTotal { get; set; }
        public double Pcharge1 { get; set; }
        public double Pdischarge1 { get; set; }
        public double Pex { get; set; }
        public double Pf { get; set; }
        public double PlocalLoadR { get; set; }
        public double PlocalLoadS { get; set; }
        public double PlocalLoadTotal { get; set; }
        public double Ppv { get; set; }
        public double Ppv1 { get; set; }
        public double Ppv2 { get; set; }
        public double Ppv3 { get; set; }
        public string PpvText { get; set; }
        public int PriorityChoose { get; set; }
        public double Pself { get; set; }
        public double Psystem { get; set; }
        public double RLoadVol { get; set; }
        public double RLocalEnergy { get; set; }
        public string SerialNum { get; set; }
        public double SLoadVol { get; set; }
        public double SLocalEnergy { get; set; }
        public int Soc { get; set; }
        public string SocText { get; set; }
        public string SphBean { get; set; }
        public int SpStatus { get; set; }
        public int Status { get; set; }
        public string StatusText { get; set; }
        public int SysFaultWord { get; set; }
        public int SysFaultWord1 { get; set; }
        public int SysFaultWord2 { get; set; }
        public int SysFaultWord3 { get; set; }
        public int SysFaultWord4 { get; set; }
        public int SysFaultWord5 { get; set; }
        public int SysFaultWord6 { get; set; }
        public int SysFaultWord7 { get; set; }
        public int SysStatus { get; set; }
        public int SystemFault { get; set; }
        public int SystemWarn { get; set; }
        public string Time { get; set; }
        public double TimeTotal { get; set; }
        public double UpsFac { get; set; }
        public double UpsPac1 { get; set; }
        public double UpsPac2 { get; set; }
        public double UpsVac1 { get; set; }
        public int UwSysWorkMode { get; set; }
        public double Vac1 { get; set; }
        public double Vac2 { get; set; }
        public double Vbat { get; set; }
        public double Vbat1 { get; set; }
        public double Vpv1 { get; set; }
        public double Vpv2 { get; set; }
        public double Vpv3 { get; set; }
        public int WarnCode { get; set; }
        public int WarnCode1 { get; set; }
        public string WarnText { get; set; }
        public bool WithTime { get; set; }

        [JsonIgnore]
        public DateTimeOffset TS { get; set; }

        #endregion Properties
    }
}
