using Newtonsoft.Json;

namespace EnergyAutomate.Growatt
{
    public class DeviceMinLastData
    {
        #region Properties

        public int Address { get; set; }
        public bool Again { get; set; }
        public string? Alias { get; set; }
        public string? BatSn { get; set; }
        public int BatteryNo { get; set; }
        public string? BatterySN { get; set; }
        public double Bdc1ChargePower { get; set; }
        public double Bdc1ChargeTotal { get; set; }
        public double Bdc1DischargePower { get; set; }
        public double Bdc1DischargeTotal { get; set; }
        public int Bdc1FaultType { get; set; }
        public double Bdc1Ibat { get; set; }
        public double Bdc1Ibb { get; set; }
        public double Bdc1Illc { get; set; }
        public int Bdc1Mode { get; set; }
        public int Bdc1Soc { get; set; }
        public int Bdc1Status { get; set; }
        public double Bdc1Temp1 { get; set; }
        public double Bdc1Temp2 { get; set; }
        public double Bdc1Vbat { get; set; }
        public double Bdc1Vbus1 { get; set; }
        public double Bdc1Vbus2 { get; set; }
        public int Bdc1WarnCode { get; set; }
        public double Bdc2ChargePower { get; set; }
        public double Bdc2ChargeTotal { get; set; }
        public double Bdc2DischargePower { get; set; }
        public double Bdc2DischargeTotal { get; set; }
        public int Bdc2FaultType { get; set; }
        public double Bdc2Ibat { get; set; }
        public double Bdc2Ibb { get; set; }
        public double Bdc2Illc { get; set; }
        public int Bdc2Mode { get; set; }
        public int Bdc2Soc { get; set; }
        public int Bdc2Status { get; set; }
        public double Bdc2Temp1 { get; set; }
        public double Bdc2Temp2 { get; set; }
        public double Bdc2Vbat { get; set; }
        public double Bdc2Vbus1 { get; set; }
        public double Bdc2Vbus2 { get; set; }
        public int Bdc2WarnCode { get; set; }
        public int BdcBusRef { get; set; }
        public int BdcDerateReason { get; set; }
        public int BdcFaultSubCode { get; set; }
        public int BdcStatus { get; set; }
        public double BdcVbus2Neg { get; set; }
        public int BdcWarnSubCode { get; set; }
        public int BgridType { get; set; }
        public int BMerterConnectFlag { get; set; }
        public int BmsCommunicationType { get; set; }
        public double BmsCvVolt { get; set; }
        public int BmsError2 { get; set; }
        public int BmsError3 { get; set; }
        public int BmsError4 { get; set; }
        public int BmsFaultType { get; set; }
        public string? BmsFwVersion { get; set; }
        public double BmsIbat { get; set; }
        public int BmsIcycle { get; set; }
        public double BmsInfo { get; set; }
        public int BmsIosStatus { get; set; }
        public double BmsMaxCurr { get; set; }
        public string? BmsMcuVersion { get; set; }
        public double BmsPackInfo { get; set; }
        public int BmsSoc { get; set; }
        public int BmsSoh { get; set; }
        public int BmsStatus { get; set; }
        public double BmsTemp1Bat { get; set; }
        public double BmsUsingCap { get; set; }
        public double BmsVbat { get; set; }
        public double BmsVdelta { get; set; }
        public int BmsWarn2 { get; set; }
        public int BmsWarnCode { get; set; }
        public int BsystemWorkMode { get; set; }
        public long Calendar { get; set; }
        public string? DataLogSn { get; set; }
        public string? Day { get; set; }
        public double DciR { get; set; }
        public double DciS { get; set; }
        public double DciT { get; set; }
        public double DcVoltage { get; set; }
        public string? Debug1 { get; set; }
        public string? Debug2 { get; set; }
        public int DeratingMode { get; set; }
        public int DryContactStatus { get; set; }
        public double EacChargeToday { get; set; }
        public double EacChargeTotal { get; set; }
        public double EacToday { get; set; }
        public double EacTotal { get; set; }
        public double EchargeToday { get; set; }
        public double EchargeTotal { get; set; }
        public double EdischargeToday { get; set; }
        public double EdischargeTotal { get; set; }
        public double Eex1Today { get; set; }
        public double Eex1Total { get; set; }
        public double Eex2Today { get; set; }
        public double Eex2Total { get; set; }
        public double ElocalLoadToday { get; set; }
        public double ElocalLoadTotal { get; set; }
        public double EpsFac { get; set; }
        public double EpsIac1 { get; set; }
        public double EpsIac2 { get; set; }
        public double EpsIac3 { get; set; }
        public double EpsPac { get; set; }
        public double EpsPac1 { get; set; }
        public double EpsPac2 { get; set; }
        public double EpsPac3 { get; set; }
        public double EpsPf { get; set; }
        public double EpsVac1 { get; set; }
        public double EpsVac2 { get; set; }
        public double EpsVac3 { get; set; }
        public double Epv1Today { get; set; }
        public double Epv1Total { get; set; }
        public double Epv2Today { get; set; }
        public double Epv2Total { get; set; }
        public double Epv3Today { get; set; }
        public double Epv3Total { get; set; }
        public double Epv4Today { get; set; }
        public double Epv4Total { get; set; }
        public double EpvTotal { get; set; }
        public string? ErrorText { get; set; }
        public double EselfToday { get; set; }
        public double EselfTotal { get; set; }
        public double EsystemToday { get; set; }
        public double EsystemTotal { get; set; }
        public double EtoGridToday { get; set; }
        public double EtoGridTotal { get; set; }
        public double EtoUserToday { get; set; }
        public double EtoUserTotal { get; set; }
        public double Fac { get; set; }
        public int FaultType { get; set; }
        public int FaultType1 { get; set; }
        public int Gfci { get; set; }
        public double Iac1 { get; set; }
        public double Iac2 { get; set; }
        public double Iac3 { get; set; }
        public double Iacr { get; set; }
        public double InvDelayTime { get; set; }
        public double Ipv1 { get; set; }
        public double Ipv2 { get; set; }
        public double Ipv3 { get; set; }
        public double Ipv4 { get; set; }
        public bool IsAgain { get; set; }
        public int Iso { get; set; }
        public double LoadPercent { get; set; }
        public bool Lost { get; set; }
        public double NBusVoltage { get; set; }
        public int OperatingMode { get; set; }
        public double OpFullwatt { get; set; }
        public double Pac { get; set; }
        public double Pac1 { get; set; }
        public double Pac2 { get; set; }
        public double Pac3 { get; set; }
        public double Pacr { get; set; }
        public double PacToGridTotal { get; set; }
        public double PacToLocalLoad { get; set; }
        public double PacToUserTotal { get; set; }
        public double PBusVoltage { get; set; }
        public double Pex1 { get; set; }
        public double Pex2 { get; set; }
        public double Pf { get; set; }
        public double Ppv { get; set; }
        public double Ppv1 { get; set; }
        public double Ppv2 { get; set; }
        public double Ppv3 { get; set; }
        public double Ppv4 { get; set; }
        public double Pself { get; set; }
        public double Psystem { get; set; }
        public int RealOPPercent { get; set; }
        public string? SerialNum { get; set; }
        public int Status { get; set; }
        public string? StatusText { get; set; }
        public int SysFaultWord { get; set; }
        public int SysFaultWord1 { get; set; }
        public int SysFaultWord2 { get; set; }
        public int SysFaultWord3 { get; set; }
        public int SysFaultWord4 { get; set; }
        public int SysFaultWord5 { get; set; }
        public int SysFaultWord6 { get; set; }
        public int SysFaultWord7 { get; set; }
        public double Temp1 { get; set; }
        public double Temp2 { get; set; }
        public double Temp3 { get; set; }
        public double Temp4 { get; set; }
        public double Temp5 { get; set; }
        public string? Time { get; set; }
        public double TimeTotal { get; set; }
        public double TotalWorkingTime { get; set; }
        [JsonIgnore]
        public DateTimeOffset TS { get; set; }
        public int UwSysWorkMode { get; set; }
        public double Vac1 { get; set; }
        public double Vac2 { get; set; }
        public double Vac3 { get; set; }
        public double Vacr { get; set; }
        public double VacRs { get; set; }
        public double VacSt { get; set; }
        public double VacTr { get; set; }
        public double Vpv1 { get; set; }
        public double Vpv2 { get; set; }
        public double Vpv3 { get; set; }
        public double Vpv4 { get; set; }
        public int WarnCode { get; set; }
        public int WarnCode1 { get; set; }
        public string? WarnText { get; set; }
        public bool WithTime { get; set; }

        #endregion Properties
    }
}
